[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "newapp"
version = "1!0.0.1788850617"
description = "Create a new python app from template"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
    "asserttool @ git+https://github.com/jakeogh/asserttool@4bd23a06c2161e488415acde89c29537e6720cc1",
    "clicktool @ git+https://github.com/jakeogh/clicktool@4bc98af7590652693aef664af7485acde40688c2",
    "configtool @ git+https://github.com/jakeogh/configtool@8b55006499c0967cb90f307e559fe74f7712a701",
    "edittool @ git+https://github.com/jakeogh/edittool@ccf5a19e514f2606c6ae38fc86401e541dcc6de6",
    "eprint @ git+https://github.com/jakeogh/eprint@6ee1deca0c24b684eb5093247d6bd22e11f1b057",
    "filetool @ git+https://github.com/jakeogh/filetool@f972b0b7fe54b4055c2015dbbe26e53593b75359",
    "getdents @ git+https://github.com/jakeogh/python-getdents@c6e9db57f8001e7b9742df4cea05857d56478f7d",
    "globalverbose @ git+https://github.com/jakeogh/globalverbose@ed36633a3208520a523e528e9371988fc33ffea3",
    "hs @ git+https://github.com/jakeogh/hs@b33c88f35cd24e773fea6ca4758193c9e815536d",
    "licenseguesser @ git+https://github.com/jakeogh/licenseguesser@12e532bd923e1353ad65d4c7e30915ecfc174b2f",
    "mptool @ git+https://github.com/jakeogh/mptool@a8579325a458cc33c6a212685aa50e16a457ccf6",
    "portagetool @ git+https://github.com/jakeogh/portagetool@b9aa9ee04976463fa1d01ce5a92cbc70e1081ba3",
    "replace-text @ git+https://github.com/jakeogh/replace-text@485330ba225ce8862a09fd598e3f402f94c347d9",
    "retry-on-exception @ git+https://github.com/jakeogh/retry-on-exception@872a0c9e578e207ac1340987fb551381d17030db",
    "timestamptool @ git+https://github.com/jakeogh/timestamptool@9812907317982046073e96dc2e909faaa491fe4c",
    "with-chdir @ git+https://github.com/jakeogh/with-chdir@13d16ecbfb95828aaa3788a27d30da81a04242c2",
    "with-user @ git+https://github.com/jakeogh/with-user@a2926aad89168ea3d80998fead4015291ee78f42",
]
requires-python = ">=3.11"

[project.license]
text = "PUBLIC DOMAIN"

[project.urls]
Homepage = "https://github.com/jakeogh/newapp"

[project.scripts]
newapp = "newapp.newapp:cli"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
newapp = [
    "py.typed",
]
